# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoService',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название сервиса')),
                ('alias', models.SlugField(blank=True, max_length=100)),
                ('teaser', models.TextField(verbose_name='Краткое описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_velcom', models.CharField(blank=True, max_length=10, verbose_name='Velcom')),
                ('phone_mts', models.CharField(blank=True, max_length=10, verbose_name='МТС')),
                ('phone_life', models.CharField(blank=True, max_length=10, verbose_name='Life')),
                ('phone_city', models.CharField(blank=True, max_length=10, verbose_name='Городской')),
                ('work_start', models.TimeField(verbose_name='Время начала работы')),
                ('work_end', models.TimeField(verbose_name='Время завершения работы')),
                ('break_time_start', models.TimeField(verbose_name='Время начала обеда')),
                ('break_time_end', models.TimeField(verbose_name='Время завершения обеда')),
                ('holiday', models.CharField(blank=True, max_length=10, verbose_name='Сокращенные дни')),
                ('holiday_time_start', models.TimeField(verbose_name='Время начала сокращенного дня')),
                ('holiday_time_end', models.TimeField(verbose_name='Время завершения сокращенного дня')),
                ('monday', models.BooleanField(verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(verbose_name='Вторник')),
                ('wednesday', models.BooleanField(verbose_name='Среда')),
                ('thursday', models.BooleanField(verbose_name='Четверг')),
                ('friday', models.BooleanField(verbose_name='Пятница')),
                ('saturday', models.BooleanField(verbose_name='Суббота')),
                ('sunday', models.BooleanField(verbose_name='Воскресенье')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('site_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('full_desc', ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Логотип компании')),
                ('is_top', models.BooleanField(verbose_name='Выводить в топ на главной?', default=None)),
                ('latitude', models.CharField(blank=True, max_length=200, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=200, verbose_name='Долгота')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title страницы')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Автосервис',
                'verbose_name_plural': 'Автосервисы',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AutoServiceWork',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', primary_key=True, serialize=False)),
                ('comp_diag', models.BooleanField(verbose_name='Компьютерная диагностика')),
                ('rep_elect', models.BooleanField(verbose_name='Ремонт электрооборудования')),
                ('rep_gen', models.BooleanField(verbose_name='Ремонт генераторов, стартеров')),
                ('car_paint', models.BooleanField(verbose_name='Покраска авто')),
                ('rec_geo', models.BooleanField(verbose_name='Восстановление геометрии')),
                ('body_work', models.BooleanField(verbose_name='Кузовные работы, рихтовка')),
                ('welding', models.BooleanField(verbose_name='Сварочные работы')),
                ('select_paint', models.BooleanField(verbose_name='Подбор краски')),
                ('rep_bump', models.BooleanField(verbose_name='Ремонт бамперов, пластика')),
                ('rep_paint', models.BooleanField(verbose_name='Беспокрасочное удаление вмятин')),
                ('sand_blasting', models.BooleanField(verbose_name='Пескоструйная обработка')),
                ('cor_treatment', models.BooleanField(verbose_name='Антикоррозийная обработка')),
                ('autoservice', models.OneToOneField(related_name='autoservice', to='service.AutoService')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Виды работ',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название сервиса')),
                ('alias', models.SlugField(blank=True, max_length=100)),
                ('teaser', models.TextField(verbose_name='Краткое описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_velcom', models.CharField(blank=True, max_length=10, verbose_name='Velcom')),
                ('phone_mts', models.CharField(blank=True, max_length=10, verbose_name='МТС')),
                ('phone_life', models.CharField(blank=True, max_length=10, verbose_name='Life')),
                ('phone_city', models.CharField(blank=True, max_length=10, verbose_name='Городской')),
                ('work_start', models.TimeField(verbose_name='Время начала работы')),
                ('work_end', models.TimeField(verbose_name='Время завершения работы')),
                ('break_time_start', models.TimeField(verbose_name='Время начала обеда')),
                ('break_time_end', models.TimeField(verbose_name='Время завершения обеда')),
                ('holiday', models.CharField(blank=True, max_length=10, verbose_name='Сокращенные дни')),
                ('holiday_time_start', models.TimeField(verbose_name='Время начала сокращенного дня')),
                ('holiday_time_end', models.TimeField(verbose_name='Время завершения сокращенного дня')),
                ('monday', models.BooleanField(verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(verbose_name='Вторник')),
                ('wednesday', models.BooleanField(verbose_name='Среда')),
                ('thursday', models.BooleanField(verbose_name='Четверг')),
                ('friday', models.BooleanField(verbose_name='Пятница')),
                ('saturday', models.BooleanField(verbose_name='Суббота')),
                ('sunday', models.BooleanField(verbose_name='Воскресенье')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('site_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('full_desc', ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Логотип компании')),
                ('is_top', models.BooleanField(verbose_name='Выводить в топ на главной?', default=None)),
                ('latitude', models.CharField(blank=True, max_length=200, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=200, verbose_name='Долгота')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title страницы')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Автомойка',
                'verbose_name_plural': 'Автомойки',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CarWashWork',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', primary_key=True, serialize=False)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TireService',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название сервиса')),
                ('alias', models.SlugField(blank=True, max_length=100)),
                ('teaser', models.TextField(verbose_name='Краткое описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_velcom', models.CharField(blank=True, max_length=10, verbose_name='Velcom')),
                ('phone_mts', models.CharField(blank=True, max_length=10, verbose_name='МТС')),
                ('phone_life', models.CharField(blank=True, max_length=10, verbose_name='Life')),
                ('phone_city', models.CharField(blank=True, max_length=10, verbose_name='Городской')),
                ('work_start', models.TimeField(verbose_name='Время начала работы')),
                ('work_end', models.TimeField(verbose_name='Время завершения работы')),
                ('break_time_start', models.TimeField(verbose_name='Время начала обеда')),
                ('break_time_end', models.TimeField(verbose_name='Время завершения обеда')),
                ('holiday', models.CharField(blank=True, max_length=10, verbose_name='Сокращенные дни')),
                ('holiday_time_start', models.TimeField(verbose_name='Время начала сокращенного дня')),
                ('holiday_time_end', models.TimeField(verbose_name='Время завершения сокращенного дня')),
                ('monday', models.BooleanField(verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(verbose_name='Вторник')),
                ('wednesday', models.BooleanField(verbose_name='Среда')),
                ('thursday', models.BooleanField(verbose_name='Четверг')),
                ('friday', models.BooleanField(verbose_name='Пятница')),
                ('saturday', models.BooleanField(verbose_name='Суббота')),
                ('sunday', models.BooleanField(verbose_name='Воскресенье')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('site_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('full_desc', ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Логотип компании')),
                ('is_top', models.BooleanField(verbose_name='Выводить в топ на главной?', default=None)),
                ('latitude', models.CharField(blank=True, max_length=200, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=200, verbose_name='Долгота')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title страницы')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Шиномонтаж',
                'verbose_name_plural': 'Шиномонтажи',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TireServiceWork',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', primary_key=True, serialize=False)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
