# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сервиса')),
                ('alias', models.SlugField(blank=True, max_length=100)),
                ('teaser', models.TextField(verbose_name='Краткое описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_velcom', models.CharField(blank=True, max_length=10, verbose_name='Velcom')),
                ('phone_mts', models.CharField(blank=True, max_length=10, verbose_name='МТС')),
                ('phone_life', models.CharField(blank=True, max_length=10, verbose_name='Life')),
                ('phone_city', models.CharField(blank=True, max_length=10, verbose_name='Городской')),
                ('work_start', models.TimeField(null=True, verbose_name='Время начала работы')),
                ('work_end', models.TimeField(null=True, verbose_name='Время завершения работы')),
                ('break_time_start', models.TimeField(null=True, verbose_name='Время начала обеда')),
                ('break_time_end', models.TimeField(null=True, verbose_name='Время завершения обеда')),
                ('holiday', models.CharField(blank=True, max_length=10, verbose_name='Сокращенные дни')),
                ('holiday_time_start', models.TimeField(null=True, verbose_name='Время начала сокращенного дня')),
                ('holiday_time_end', models.TimeField(null=True, verbose_name='Время завершения сокращенного дня')),
                ('monday', models.BooleanField(verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(verbose_name='Вторник')),
                ('wednesday', models.BooleanField(verbose_name='Среда')),
                ('thursday', models.BooleanField(verbose_name='Четверг')),
                ('friday', models.BooleanField(verbose_name='Пятница')),
                ('saturday', models.BooleanField(verbose_name='Суббота')),
                ('sunday', models.BooleanField(verbose_name='Воскресенье')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('site_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('full_desc', ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Логотип компании')),
                ('is_top', models.BooleanField(default=None, verbose_name='Выводить в топ на главной?')),
                ('latitude', models.CharField(blank=True, max_length=200, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=200, verbose_name='Долгота')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title страницы')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Автосервисы',
                'verbose_name': 'Автосервис',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BodyRepairWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=200, verbose_name='Вид работы')),
            ],
            options={
                'verbose_name_plural': 'Кузовной ремонт',
                'verbose_name': '',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сервиса')),
                ('alias', models.SlugField(blank=True, max_length=100)),
                ('teaser', models.TextField(verbose_name='Краткое описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_velcom', models.CharField(blank=True, max_length=10, verbose_name='Velcom')),
                ('phone_mts', models.CharField(blank=True, max_length=10, verbose_name='МТС')),
                ('phone_life', models.CharField(blank=True, max_length=10, verbose_name='Life')),
                ('phone_city', models.CharField(blank=True, max_length=10, verbose_name='Городской')),
                ('work_start', models.TimeField(null=True, verbose_name='Время начала работы')),
                ('work_end', models.TimeField(null=True, verbose_name='Время завершения работы')),
                ('break_time_start', models.TimeField(null=True, verbose_name='Время начала обеда')),
                ('break_time_end', models.TimeField(null=True, verbose_name='Время завершения обеда')),
                ('holiday', models.CharField(blank=True, max_length=10, verbose_name='Сокращенные дни')),
                ('holiday_time_start', models.TimeField(null=True, verbose_name='Время начала сокращенного дня')),
                ('holiday_time_end', models.TimeField(null=True, verbose_name='Время завершения сокращенного дня')),
                ('monday', models.BooleanField(verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(verbose_name='Вторник')),
                ('wednesday', models.BooleanField(verbose_name='Среда')),
                ('thursday', models.BooleanField(verbose_name='Четверг')),
                ('friday', models.BooleanField(verbose_name='Пятница')),
                ('saturday', models.BooleanField(verbose_name='Суббота')),
                ('sunday', models.BooleanField(verbose_name='Воскресенье')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('site_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('full_desc', ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Логотип компании')),
                ('is_top', models.BooleanField(default=None, verbose_name='Выводить в топ на главной?')),
                ('latitude', models.CharField(blank=True, max_length=200, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=200, verbose_name='Долгота')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title страницы')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Автомойки',
                'verbose_name': 'Автомойка',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CarWashWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ElectricianWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=200, verbose_name='Вид работы')),
            ],
            options={
                'verbose_name_plural': 'Автоэлектрика',
                'verbose_name': '',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TireService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сервиса')),
                ('alias', models.SlugField(blank=True, max_length=100)),
                ('teaser', models.TextField(verbose_name='Краткое описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_velcom', models.CharField(blank=True, max_length=10, verbose_name='Velcom')),
                ('phone_mts', models.CharField(blank=True, max_length=10, verbose_name='МТС')),
                ('phone_life', models.CharField(blank=True, max_length=10, verbose_name='Life')),
                ('phone_city', models.CharField(blank=True, max_length=10, verbose_name='Городской')),
                ('work_start', models.TimeField(null=True, verbose_name='Время начала работы')),
                ('work_end', models.TimeField(null=True, verbose_name='Время завершения работы')),
                ('break_time_start', models.TimeField(null=True, verbose_name='Время начала обеда')),
                ('break_time_end', models.TimeField(null=True, verbose_name='Время завершения обеда')),
                ('holiday', models.CharField(blank=True, max_length=10, verbose_name='Сокращенные дни')),
                ('holiday_time_start', models.TimeField(null=True, verbose_name='Время начала сокращенного дня')),
                ('holiday_time_end', models.TimeField(null=True, verbose_name='Время завершения сокращенного дня')),
                ('monday', models.BooleanField(verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(verbose_name='Вторник')),
                ('wednesday', models.BooleanField(verbose_name='Среда')),
                ('thursday', models.BooleanField(verbose_name='Четверг')),
                ('friday', models.BooleanField(verbose_name='Пятница')),
                ('saturday', models.BooleanField(verbose_name='Суббота')),
                ('sunday', models.BooleanField(verbose_name='Воскресенье')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('site_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('full_desc', ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Логотип компании')),
                ('is_top', models.BooleanField(default=None, verbose_name='Выводить в топ на главной?')),
                ('latitude', models.CharField(blank=True, max_length=200, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=200, verbose_name='Долгота')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title страницы')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Шиномонтажи',
                'verbose_name': 'Шиномонтаж',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TireServiceWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='body_repair_work',
            field=models.ManyToManyField(to='service.BodyRepairWork', related_name='body_repair_work'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='autoservice',
            name='electrician_work',
            field=models.ManyToManyField(to='service.ElectricianWork', related_name='electrician_work'),
            preserve_default=True,
        ),
    ]
