# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20150717_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoservice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='break_time_end',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='break_time_start',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='full_desc',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='holiday_time_end',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='holiday_time_start',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='phone_city',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='phone_city2',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='phone_life',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='phone_life2',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='phone_mts',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='phone_mts2',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='phone_velcom',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='phone_velcom2',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='teaser',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='work_start',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='address',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='break_time_end',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='break_time_start',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='full_desc',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='holiday_time_end',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='holiday_time_start',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='phone_city',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='phone_city2',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='phone_life',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='phone_life2',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='phone_mts',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='phone_mts2',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='phone_velcom',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='phone_velcom2',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='teaser',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='title',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='work_start',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='break_time_end',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='break_time_start',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='full_desc',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='holiday_time_end',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='holiday_time_start',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='phone_city',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='phone_city2',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='phone_life',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='phone_life2',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='phone_mts',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='phone_mts2',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='phone_velcom',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='phone_velcom2',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='teaser',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='tireservice',
            name='work_start',
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0435\u0440\u0432\u0438\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0435\u0440\u0432\u0438\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='tireservice',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0435\u0440\u0432\u0438\u0441\u0430'),
        ),
    ]
